
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "@/Components/sessionProviderWrapper";
import { ThemeProvider } from "@/Components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProviderWrapper>
        <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <main className="p-4">
            {children}
          </main>
          </ThemeProvider>
        </body>
      </SessionProviderWrapper>
    </html>
  );
}
